version: '3.8'

services:
  # 1. IL DATABASE LOCALE
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db # Questo salva i dati così non spariscono se spengo docker

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database # Il backend ora aspetta che il database sia acceso
    env_file:
      - ./backend/.env
    environment:
      # Sovrascriviamo l'URI del file .env 
      # e diciamo all'app di puntare al container del database.
      # Docker reindirizzerà "database" al container MongoDB.
      - MONGODB_URI=mongodb://database:27017/notes-app-db

  frontend:
    build: ./frontend/notes-app
    ports:
      - "5173:5173"
    depends_on:
      - backend

# Dichiariamo il volume per il database
volumes:
  db-data: